package com.niazbaharudeen.back_end.dtos;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class MovieResponseDTO {

    @JsonProperty("id") // map TMDB ID to an external ID we keep track of
    private int externalId;

    private String title;

    @JsonProperty("poster_path") // map url of movie image to the JSON property in the response
    private String url;

    @JsonProperty("release_date")
    private String releaseDate;

    private Boolean isFavorited;

    // manual setters to override Lombok's autogenerated ones to make necessary
    // additions/revisions

    public void setUrl(String url) {
        // provided url is only a fragment of the path, setter completes the url
        this.url = "https://image.tmdb.org/t/p/w500" + url;
    }

    public void setReleaseDate(String releaseDate) {
        // provided release date has month and day, we use regex to separate them
        // and only keep the year
        this.releaseDate = releaseDate.split("-")[0];
    }

}
